const imageUrl = "/collections/templates";

const collections_content = [
  {
    title: "Everyday Living Architecture",
    url: "",
    assetsImage: [`${imageUrl}/1.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Sonoran Travel Buddies",
    url: "",
    assetsImage: [`${imageUrl}/2.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Homedroid Home Services",
    url: "",
    assetsImage: [`${imageUrl}/3.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Crypto, ICO, Web3 Website",
    url: "",
    assetsImage: [`${imageUrl}/4.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Digitalis Branding Agency",
    url: "",
    assetsImage: [`${imageUrl}/5.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Sky No Limit Creative",
    url: "",
    assetsImage: [`${imageUrl}/6.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Next Generator AI Web",
    url: "",
    assetsImage: [`${imageUrl}/7.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Solutions Hub Contractor",
    url: "",
    assetsImage: [`${imageUrl}/8.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "International Conference Website",
    url: "",
    assetsImage: [`${imageUrl}/9.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Our Financial Calculator",
    url: "",
    assetsImage: [`${imageUrl}/10.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Planning Your Career Success",
    url: "",
    assetsImage: [`${imageUrl}/11.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Invest at The Perfect Time",
    url: "",
    assetsImage: [`${imageUrl}/12.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Accounting Made Simple",
    url: "",
    assetsImage: [`${imageUrl}/13.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "The Right Financial Partner",
    url: "",
    assetsImage: [`${imageUrl}/14.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Cloud Deployment in Seconds",
    url: "",
    assetsImage: [`${imageUrl}/15.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Close Your Every Deals",
    url: "",
    assetsImage: [`${imageUrl}/16.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Open AI as Your Partner",
    url: "",
    assetsImage: [`${imageUrl}/17.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Blogging Made Easier",
    url: "",
    assetsImage: [`${imageUrl}/18.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "New Ways to Build Apps",
    url: "",
    assetsImage: [`${imageUrl}/19.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Record and Centralise Feedback",
    url: "",
    assetsImage: [`${imageUrl}/20.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Automate Workflow with AI",
    url: "",
    assetsImage: [`${imageUrl}/21.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Revolutionize Your Business",
    url: "",
    assetsImage: [`${imageUrl}/22.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Everything Make Sense Web",
    url: "",
    assetsImage: [`${imageUrl}/23.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Smart Scheduling by AI",
    url: "",
    assetsImage: [`${imageUrl}/24.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
  {
    title: "Award-Winning Development Web",
    url: "",
    assetsImage: [`${imageUrl}/25.png`],
    desc: "A dedicated landing page designed to promote Islamic educational resources and programs, with a modern and intuitive layout.",
    purchase_number: 1,
  },
];
export default collections_content;
